import type { Metadata } from "next";
import "@/styles/globals.css";
import 'katex/dist/katex.min.css'
import 'github-markdown-css/github-markdown.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="markdown-body">
          {children}
        </div>
      </body>
    </html>
  );
}
